//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Greetings.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tb_cards
    {
        public int ca_id { get; set; }
        public string ca_pic { get; set; }
        public Nullable<int> ca_fk_c { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [RegularExpression("[A-Za-z]*", ErrorMessage = "Use alphabets only")]
        public string ca_name { get; set; }
    
        public virtual tb_category tb_category { get; set; }
    }
}
