//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Greetings.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class tb_feedback
    {
        public int FD_id { get; set; }
        [Required]
        public string FD_reaction { get; set; }
        [EmailAddress]
        [Required(ErrorMessage = "This field is required")]
        public string FD_email { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string FD_message { get; set; }
    }
}
