//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Greetings.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_trx
    {
        public int tr_id { get; set; }
        public string tr_to { get; set; }
        public string tr_cardname { get; set; }
        public Nullable<System.DateTime> tr_time { get; set; }
        public Nullable<int> tr_fk_u { get; set; }
    
        public virtual tb_userdetails tb_userdetails { get; set; }
    }
}
