//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Greetings.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tb_userdetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_userdetails()
        {
            this.tb_trx = new HashSet<tb_trx>();
        }

        public int U_id { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [RegularExpression("[A-Z a-z]*", ErrorMessage = "Use alphabets only")]
        public string U_fname { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [RegularExpression("[A-Z a-z]*", ErrorMessage = "Use alphabets only")]
        public string U_lname { get; set; }
        [EmailAddress]
        [Required(ErrorMessage = "This field is required")]
        public string U_email { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string U_pass { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [RegularExpression("[A-Z a-z]*", ErrorMessage = "Use alphabets only")]
        public string U_country { get; set; }
        [RegularExpression("[0-9]*", ErrorMessage = "Use numeric values only")]
        [Required(ErrorMessage = "This field is required")]
        public string U_number { get; set; }
        public Nullable<int> u_role_id { get; set; }
    
        public virtual tb_roles tb_roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_trx> tb_trx { get; set; }
    }
}
